### ISSUE TITLE
Sound Sender doesn't work with samples starting with numbers

### ISSUE THREAD

**Issue by HighHarmonics2** [Bubobubobubobubo/sardine#121]
Issue

- dirt~ sample names starting with numbers generate errors when specific samples are referenced using the colon.
- dirt~ sample names starting with numbers that contain numbers and letters generate errors whether there is a specific colon ref or not.

examples - number names:
`S('808').out(i, div=1)`   #this works
`S('808:0').out(i, div=1)` # this errors:   "Non valid token: 808:0: Unexpected token Token('COLON', ':')"

number + letter names:
`S('808hc')`  # fails: "AttributeError: 'PatternStr' object has no attribute 'raw'"
`S('808hc:0')` # fails: "AttributeError: 'PatternStr' object has no attribute 'raw'"

**Comment by Bubobubobubobubo** [comment]
Hi! Sorry for not answering sooner, the rewrite is now done, I can get back to chasing these bugs :)

The rules actually make sense if you really think hard about them but I will try to see what I can do to make it smoother and more cohesive with how SuperDirt usually handle sample names:
- `808`: it works because it's a number so it's always valid.
- `808:0`: this is a sample selection on a number, it fails.
- `808hc`: sample names can't start with a number, it fails.
- `808hc:0`: // but with a sample selection, it fails.

**Comment by HighHarmonics2** [comment]
Thanks. No urgency here. I would say to prioritize this only after you have documentation available for 0.2.

**Comment by Bubobubobubobubo** [comment]
This feature was implemented recently. It was discarded very quickly because it broke most features of SPL. Somebody can probably re-open the issue in the future if they have the answer to this problem but I think that I don't.

Most Sardine users got accustomed to the restriction of using sample names in lowercase and without prepending a number: `808kit` -> `kit808`.
