### ISSUE TITLE
amphibian variable access fails for p in swim function

### ISSUE THREAD

**Issue by HighHarmonics2** [Bubobubobubobubo/sardine#194]
Using an amphibian variable for period value works in Player but fails in swim function.

```
V.a = 0.6
Pb >> d("bd", period='(v a)')  # works, change V.a value and period in player changes

@swim
def ampVar(p='(v a)', i=0):
    D("bd")
    again(ampVar, p='(v a)', i=i+1) # fails
```
Sardine.scheduler.errors.BadPeriodError: Period must be a float or integer, not '(v a)'

Is there any other way to make amphibian variable work for period in swim?

**Comment by Bubobubobubobubo** [comment]
I'm not sure if this should be posted on GitHub given that it is more related to usage and not really a bug. Discord? In short, this is the expected behavior, see [Patterning Everything](https://sardine.raphaelforment.fr/diving_deeper/patterning_everything.html). Again is a normal Python function, not a sender. Thus, you can't use a pattern directly and must explicitly convert to sender `P('(v a)', i)`.

It is not possible (to my knowledge) to accept patterns as arguments of `again`.
