### ISSUE TITLE
Cannot play SuperDirt samples 808 and 909 with an index

### ISSUE THREAD

**Issue by pierredewilde** [Bubobubobubobubo/sardine#252]
`Pa * d('808')` is played correctly but `Pa * d('808:0')` generated an error:

`ValueError: Cannot pattern an empty sequence: []`

Same for `Pa * d('909')` and `Pa * d('909:0')`.

All other samples play correctly.

Please note that `808` and `909` are the only SuperDirt samples without at least a letter in their names.

**Comment by Bubobubobubobubo** [comment]
Hi! Yes, this is unfortunate but it is due to how the base pattern language is working in Sardine. Some other patttern language features are hindering the possibility to use sample folders whose name is only based on numbers.

I took the habit of renaming the few problematic ones. It's better than loosing the ability to work with numbers in the pattern itself :)

**Comment by pierredewilde** [comment]
Got it.

In that case, you should change the corresponding line in [6.3. Synths / Samples](https://sardine.raphaelforment.fr/getting_started/samples_and_synths.html)


`Pa * d('808:[0:5,1]', p=0.5, room=1,size=0.5,dry=0.4)`

should be removed or restricted to 

`Pa * d('808', p=0.5, room=1,size=0.5,dry=0.4)`

**Comment by Bubobubobubobubo** [comment]
Done : 3f96c93. Thanks for catching this one!

**Comment by Bubobubobubobubo** [comment]
It is now possible to use numbers only for sample names:
```python
Pa * d("808", n="0~20", p=0.5)
Pb * d(". 808", n="10~20", p="0.25|0.5", speed="[1:4]")
```
I'm closing this issue, please re-open a new one if needed.
