### ISSUE TITLE
Inline editor is sometimes rhythmically interrupted

### ISSUE THREAD

**Issue by Rhoumi** [Bubobubobubobubo/sardine#51]
The inline editor seems to have some kinds of spasms.

**Comment by Bubobubobubobubo** [comment]
It might be because `ptpython` is not really `asyncio`. It can surely be fixed but in the meantime, try to disable some completion options in the contextual menu (`F2`). You might find that some of them have quite a big impact on these rhythmic hiccups.

The inline editor is experimental, and has been implemented as a way to quickly demo **Sardine**. If you should ever play with it over a long period of time, a text editor is definitely recommended.

**Comment by Bubobubobubobubo** [comment]
It should be possible (even if non-orthodox) to have two event loops working together on two different threads. Asyncio is made to avoid relying on threads but this looks like a case where an exception makes sense:
- run the clock on a light/fast asyncio loop
- run the editor on its own thread so that it never blocks execution.

**Comment by Bubobubobubobubo** [comment]
The inline editor was a nightmare to debug and required a pretty hacky refactoring to work properly. I removed it entirely, better to keep the idea floating around until a better solution is found!
